services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile_builder
      tags:
        - test-docker:builder
  minimal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDER_IMAGE=test-docker:builder
      tags:
        - test-docker:minimal
    depends_on: 
      - builder
  more:
    build: 
      context: .
      dockerfile: Dockerfile_more
      args:
        - BASE_IMAGE=test-docker:minimal
      tags:
        - test-docker:more
    depends_on: 
      - minimal
      