services:
  minimal:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - test-docker:minimal
  more:
    build: 
      context: .
      dockerfile: Dockerfile_more
      args:
        - BASE_IMAGE=test-docker:minimal
      tags:
        - test-docker:more
    depends_on: 
      - minimal
      