services:
  minimal:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - type=gha
      cache_to: 
        - type=gha,mode=max
      tags:
        - test-docker:minimal
  more:
    build: 
      context: .
      dockerfile: Dockerfile_more
      cache_from: 
        - type=gha
      cache_to: 
        - type=gha,mode=max
      tags:
        - test-docker:more
    depends_on: 
      - minimal
      